version: "3.9"

services:

  frontend:
    build: ./frontend
    container_name: purificadora_frontend
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    container_name: purificadora_backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    restart: always  

  postgres:
    image: postgres:15
    container_name: purificadora_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - purificadora_postgres_data:/var/lib/postgresql/data
      # Solo se ejecuta la primera vez que el volumen está vacío (init de Postgres)
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: purificadora_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5051:80"
    depends_on:
      - postgres
    volumes:
      - purificadora_pgadmin_data:/var/lib/pgadmin

volumes:
  purificadora_postgres_data:
  purificadora_pgadmin_data: